CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Human                   MFQIPEFEPSEQEDSSSAERGLGPSPAGDGPSGSGKHHRQAPGLLWDASHQQEQPTSSSH
Water_Buffalo           MFQIPEFEQSEQEDSSPADRGLGPSPTGDRPPGLSKHWLTAPGLLGEAGHQQGQPAGSSH
Sunda_Flyin_Lemur       MFQIPEFEPSEQEDSSSADRGLGPSPAGDRPPGPGKHRCPAPGLLGDASHQQGQATSSTH
Siberian_Tiger          MFQIPEFEPSEQEDSSPTDRGLGPSPTGDRPRGPGKHQRTAPGLLGEAGHQQGQPASSNH
Dog                     MFQIPEFEPSEQEDSSPANRGLGPSPTGDRPPSPGKHQQTAPGLLGEAGHQQGQPASRKH
Sea_Otter               MFQIPEFEPSEQEDSSPADRGLGPSPTGDQPPGLGKHLQTAPGLLGEAGHQQGQPASSSH
Ferret                  MFQIPEFEPSEQEDSSPADRGLGPSPTGDQPPGLGKHLQTAPGLLGEAGHQQGQPASSSH
Pacific_Walrus          MFQIPEFEPSEQEDSSPADRGLGPSPTGDRPPGPGKHRQTAPGLLGEAGHQQGQPASSNH
Hawaiian_Monk_Seal      MFQIPEFEPSEQEDSSPALRGLGPSPTGDRPPGPGKHRQTAPGLLGEAGHQQGQPASSNH
Ursus_BAD               MFQIPEFEPSEQEDSSPADRGLGPSPTGDQPPGPGKHRQTAPGLLGEAAQPQGQPASSNH
Giant_Panda             MFQIPEFEPSEQEDSSPADRGLGPSPTGDQPPGPGKHRQTAPGLLGEAAHPQGQPASSNH
                        ******** *******.: *******:** * . .**   ***** :*.: * *.:. .*

Human                   HGGAGAVEIRSRHSSYPAGTEDDEGM-GEEPSPFRGRSRSAPPNLWAAQRYGRELRRMSD
Water_Buffalo           HGGTGAVETRSRHSSYPAGPEDNEGTEEEDLGPFRGRSRSAPPNLWAAQRYGRELRRMSD
Sunda_Flyin_Lemur       HGGAGAVETRSRHSSYPEGTEVDEGL-EEEPSPFRGRSRSAPPNLWAAQRYGRELRRMSD
Siberian_Tiger          HGGAGAVETRSRHSSYPAGTEEDEGTEEEEPSPFRGRSRSAPPNLWAALRYGRELRRMSD
Dog                     HGGAGA-ETRSRHSSFPAGTDEDEGMEEEELSPFRGRSSSAPPNLCAARRYGRELRRMSD
Sea_Otter               HGGAGAVETRSRHSSYPAGTEEDEEMEEEELSPFRGRSQSAPPNLCAALRYGRELRRMSD
Ferret                  HGGAGAVETRSRHSSYPAGTEEDEGMEEEELSPFRGRSRSAPPNLCAALRYGRELRRMSD
Pacific_Walrus          HGGAGAVETRSRHSSYPAGSEEDEGMEEEELSPFRGRSSSAPPNLCAALRYGRELRRMSD
Hawaiian_Monk_Seal      HGGAGAVETRSRHSSYPAGTEEDEGVEEEELSPFRGRSSSAPPNLCAALRYGRELRRMSD
Ursus_BAD               HGGAGAVEPRSRHSSYPAGTEEDEGLEEEELSPFRGRSSSAPPNLCAALRYGRELRRMSD
Giant_Panda             HGGAGAVEPRSRHSSYPAGTEEDEGLEEEELSPFRGRSSSAPPNLCAALRYGRELRRMSD
                        ***:** * ******:* *.: :*    *: .****** ****** ** ***********

Human                   EFVDSFKKGLPRPKSAGTATQMRQSSSWTRVFQSWWDRNLGRGSSAPSQ
Water_Buffalo           EFHVSF-KGLPRPKSAGTATQMRQSPSWTRFLQSWLSRNLGRGGSAPSQ
Sunda_Flyin_Lemur       EFQGSF-KGLPRPKSAGTATQMRQSSSWTRIIQSWWDRNLGRGGSTPSQ
Siberian_Tiger          EFQGSF-KGLPRPKSAGTATQMRQSPSWTRFIQSWWDRNLGRGGSAPSQ
Dog                     EFQGSF-KGLPRPKSAGTATQMRQSPSWTRVIQSWWDRNLGRGGSAPSQ
Sea_Otter               EFQGSF-KGLPRPKSAGTATQMRQSPSWTRVIQSWWDRNLGRGGSAPSQ
Ferret                  EFQGSF-KGLPRPKSAGTATQMRQSPSWTRVIQSWWDRNLGRGGSAPSQ
Pacific_Walrus          EFQGSF-KGLPRPRSAGTATQMRQSPSWTRVIQSWWDRNLGRGGSAPSQ
Hawaiian_Monk_Seal      EFQGSF-KGLPRPKSAGTATQMRQSPSWTRVIQSWWDRNLGRGASAPSQ
Ursus_BAD               EFQGSF-KGLPRPKSAGTATQMRQSPSWTRVIQSW--------------
Giant_Panda             EFQGSF-KGLPRPKSAGTATQMRQSPSWTRVIQSWWDRNLGRGGSAPSQ
                        **  ** ******.***********.****.:***              
